export const COUNTRY_CODES = [
  { name: 'Trung Quốc đại lục', code: '+86', popular: true },
  { name: 'Việt Nam', code: '+84', popular: true },
  { name: 'Hoa Kỳ', code: '+1', popular: true },
  { name: 'Đặc khu hành chính Hồng Kông', code: '+852', popular: true },
  { name: 'Đặc khu hành chính Ma Cao', code: '+853' },
  { name: 'Đài Loan, Trung Quốc', code: '+886' },
  { name: 'Bỉ', code: '+32' },
  { name: 'Úc', code: '+61' },
  { name: 'Pháp', code: '+33' },
  { name: 'Canada', code: '+1' },
  { name: 'Nhật Bản', code: '+81' },
  { name: 'Singapore', code: '+65' },
  { name: 'Hàn Quốc', code: '+82' },
  { name: 'Malaysia', code: '+60' },
  { name: 'Vương quốc Anh', code: '+44' },
  { name: 'Ý', code: '+39' },
  { name: 'Đức', code: '+49' },
  { name: 'Nga', code: '+7' },
  { name: 'Kazakhstan', code: '+7' },
  { name: 'Sri Lanka', code: '+94' },
  { name: 'Saint Pierre và Miquelon', code: '+508' },
  { name: 'San Marino', code: '+378' },
  { name: 'Saint Vincent và Grenadines', code: '+1784' },
  { name: 'São Tomé và Príncipe', code: '+239' },
  { name: 'Ả Rập Xê Út', code: '+966' },
  { name: 'Zanzibar', code: '+259' },
  { name: 'Cộng hòa Seychelles', code: '+248' },
  { name: 'Síp', code: '+357' },
  { name: 'Senegal', code: '+221' },
  { name: 'Sierra Leone', code: '+232' },
  { name: 'Samoa thuộc Mỹ', code: '+1684' },
  { name: 'Slovakia', code: '+421' },
  { name: 'Slovenia', code: '+386' },
  { name: 'Tunisia', code: '+216' },
  { name: 'Đảo Ascension', code: '+247' },
  { name: 'Trinidad và Tobago', code: '+1868' },
  { name: 'Tex và Caicos', code: '+1649' },
  { name: 'Tonga', code: '+676' },
  { name: 'Tanzania', code: '+255' },
  { name: 'Thái Lan', code: '+66' },
  { name: 'Somalia', code: '+252' },
  { name: 'quần đảo Solomon', code: '+677' },
  { name: 'Surinam', code: '+597' },
  { name: 'Sudan', code: '+249' },
  { name: 'Swaziland', code: '+268' },
  { name: 'Tuvalu', code: '+688' },
  { name: 'Samoa, Tây', code: '+685' },
  { name: 'El Salvador', code: '+503' },
  { name: 'Serbia', code: '+381' },
  { name: 'Nam Phi', code: '+27' },
  { name: 'Namibia', code: '+264' },
  { name: 'Mexico', code: '+52' },
  { name: 'Mozambique', code: '+258' },
  { name: 'Monaco', code: '+377' },
  { name: 'Ma-rốc', code: '+212' },
  { name: 'Moldova', code: '+373' },
  { name: 'Myanmar', code: '+95' },
  { name: 'Micronesia', code: '+691' },
  { name: 'Peru', code: '+51' },
  { name: 'Nauru', code: '+674' },
  { name: 'Nepal', code: '+977' },
  { name: 'Nicaragua', code: '+505' },
  { name: 'Thụy Sĩ', code: '+41' },
  { name: 'Thụy Điển', code: '+46' },
  { name: 'Georgia', code: '+995' },
  { name: 'Quần đảo Wallis và quần đảo Futuna', code: '+1681' },
  { name: 'Bồ Đào Nha', code: '+351' },
  { name: 'Palau', code: '+680' },
  { name: 'Đảo Norfolk', code: '+672' },
  { name: 'Na Uy', code: '+47' },
  { name: 'Niue', code: '+683' },
  { name: 'Nigeria', code: '+234' },
  { name: 'Niger', code: '+227' },
  { name: 'Bangladesh', code: '+880' },
  { name: 'Jamaica', code: '+1658' },
  { name: 'Curaçao', code: '+599' },
  { name: 'Guyana', code: '+592' },
  { name: 'Liechtenstein', code: '+423' },
  { name: 'Kosovo', code: '+383' },
  { name: 'Montenegro', code: '+382' },
  { name: 'Aruba', code: '+297' },
  { name: 'Nam Sudan', code: '+211' },
  { name: 'Saint Kitts và Nevis', code: '+1869' },
  { name: 'Guatemala', code: '+502' },
  { name: 'Chile', code: '+56' },
  { name: 'Gibraltar', code: '+350' },
  { name: 'Vùng biển Caribe thuộc Hà Lan', code: '+599' },
  { name: 'Đông Timor', code: '+670' },
  { name: 'New Caledonia', code: '+687' },
  { name: 'Puerto Rico', code: '+1939' },
  { name: 'người Dominica (1849)', code: '+1849' },
  { name: 'người Dominica (1829)', code: '+1829' },
  { name: 'thánh Lucia', code: '+1758' },
  { name: 'St. Martin, Hà Lan', code: '+1721' },
  { name: 'Anguilla', code: '+1264' },
  { name: 'Tajikistan', code: '+992' },
  { name: 'Palestine', code: '+970' },
  { name: 'Đảo Man', code: '+833' },
  { name: 'Áo đấu', code: '+832' },
  { name: 'Guernsey', code: '+826' },
  { name: 'Chad', code: '+235' },
  { name: 'Zambia', code: '+260' },
  { name: 'Uzbekistan', code: '+998' },
  { name: 'Uruguay', code: '+598' },
  { name: 'Ukraina', code: '+380' },
  { name: 'Uganda', code: '+256' },
  { name: 'Brunei', code: '+673' },
  { name: 'Venezuela', code: '+58' },
  { name: 'Quần đảo Virgin (thuộc Anh)', code: '+1284' },
  { name: 'Quần đảo Virgin (lãnh thổ của Hoa Kỳ)', code: '+1340' },
  { name: 'Vanuatu', code: '+678' },
  { name: 'Tokelau', code: '+690' },
  { name: 'Turkmenistan', code: '+993' },
  { name: 'Tây ban nha', code: '+34' },
  { name: 'Hy Lạp', code: '+30' },
  { name: 'Bờ Biển Ngà', code: '+225' },
  { name: 'Jordan', code: '+962' },
  { name: 'Indonesia', code: '+62' },
  { name: 'Ấn Độ', code: '+91' },
  { name: 'Israel', code: '+972' },
  { name: 'Iran', code: '+98' },
  { name: 'Iraq', code: '+964' },
  { name: 'Yemen', code: '+967' },
  { name: 'Armenia', code: '+374' },
  { name: 'Jamaica (1876)', code: '+1876' },
  { name: 'Syria', code: '+963' },
  { name: 'Hungary', code: '+36' },
  { name: 'Thổ Nhĩ Kỳ', code: '+90' },
  { name: 'Montserrat', code: '+1664' },
  { name: 'Quần đảo Falkland', code: '+500' },
  { name: 'Đan Mạch', code: '+45' },
  { name: 'Guinea Xích đạo', code: '+240' },
  { name: 'Burundi', code: '+257' },
  { name: 'Burkina Faso', code: '+226' },
  { name: 'Bhutan', code: '+975' },
  { name: 'Botswana', code: '+267' },
  { name: 'Belize', code: '+501' },
  { name: 'Bolivia', code: '+591' },
  { name: 'Ba Lan', code: '+48' },
  { name: 'Bosnia và Herzegovina', code: '+387' },
  { name: 'Puerto Rico (1787)', code: '+1787' },
  { name: 'Diego Garcia', code: '+246' },
  { name: 'Togo', code: '+228' },
  { name: 'Dominic', code: '+1767' },
  { name: 'Cape Verde', code: '+238' },
  { name: 'Phần Lan', code: '+358' },
  { name: 'Fiji', code: '+679' },
  { name: 'Philippines', code: '+63' },
  { name: 'Trung Phi', code: '+236' },
  { name: 'Guiana thuộc Pháp', code: '+594' },
  { name: 'Polynesia thuộc Pháp', code: '+689' },
  { name: 'Quần đảo Faroe', code: '+298' },
  { name: 'Eritrea', code: '+291' },
  { name: 'Ecuador', code: '+593' },
  { name: 'người Dominica (1809)', code: '+1809' },
  { name: 'Iceland', code: '+354' },
  { name: 'Benin', code: '+229' },
  { name: 'Bulgaria', code: '+359' },
  { name: 'Estonia', code: '+372' },
  { name: 'Ireland', code: '+353' },
  { name: 'Ethiopia', code: '+251' },
  { name: 'Ai Cập', code: '+20' },
  { name: 'Azerbaijan', code: '+994' },
  { name: 'Oman', code: '+968' },
  { name: 'UAE', code: '+971' },
  { name: 'Argentina', code: '+54' },
  { name: 'Afghanistan', code: '+93' },
  { name: 'Algeria', code: '+213' },
  { name: 'Albania', code: '+355' },
  { name: 'Andorra', code: '+376' },
  { name: 'Angola', code: '+244' },
  { name: 'Antigua và Barbuda', code: '+1268' },
  { name: 'Bermuda', code: '+1441' },
  { name: 'Belarus', code: '+375' },
  { name: 'Brazil', code: '+55' },
  { name: 'Panama', code: '+507' },
  { name: 'Bahrain', code: '+973' },
  { name: 'Paraguay', code: '+595' },
  { name: 'Pakistan', code: '+92' },
  { name: 'Bahamas', code: '+1242' },
  { name: 'Papua New Guinea', code: '+675' },
  { name: 'Barbados', code: '+1246' },
  { name: 'Áo', code: '+43' },
  { name: 'New Zealand', code: '+64' },
  { name: 'Gambia', code: '+220' },
  { name: 'Mông Cổ', code: '+976' },
  { name: 'Libya', code: '+218' },
  { name: 'Liberia', code: '+231' },
  { name: 'Litva', code: '+370' },
  { name: 'Lebanon', code: '+961' },
  { name: 'Lào', code: '+856' },
  { name: 'Lesotho', code: '+266' },
  { name: 'Latvia', code: '+371' },
  { name: 'Quần đảo Cook', code: '+682' },
  { name: 'Kenya', code: '+254' },
  { name: 'Croatia', code: '+385' },
  { name: 'Kuwait', code: '+965' },
  { name: 'Luxembourg', code: '+352' },
  { name: 'Rwanda', code: '+250' },
  { name: 'Romania', code: '+40' },
  { name: 'Mauritania', code: '+222' },
  { name: 'Mauritius', code: '+230' },
  { name: 'Quần đảo Marshall', code: '+692' },
  { name: 'Martinique', code: '+596' },
  { name: 'Macedonia', code: '+389' },
  { name: 'Quần đảo Mariana', code: '+1670' },
  { name: 'Mali', code: '+223' },
  { name: 'Malawi', code: '+265' },
  { name: 'Malta', code: '+356' },
  { name: 'Maldives', code: '+960' },
  { name: 'Madagascar', code: '+261' },
  { name: 'Comoros', code: '+269' },
  { name: 'Quần đảo Cayman', code: '+1345' },
  { name: 'Qatar', code: '+974' },
  { name: 'Hà Lan', code: '+31' },
  { name: 'Triều Tiên', code: '+850' },
  { name: 'Haiti', code: '+509' },
  { name: 'Guam', code: '+1671' },
  { name: 'Guadeloupe', code: '+590' },
  { name: 'Cuba', code: '+53' },
  { name: 'Greenland', code: '+299' },
  { name: 'Grenada', code: '+1473' },
  { name: 'Costa Rica', code: '+506' },
  { name: 'Colombia', code: '+57' },
  { name: 'Cộng hòa Dân chủ Congo', code: '+243' },
  { name: 'Honduras', code: '+504' },
  { name: 'Đảo Vik', code: '+1808' },
  { name: 'Kiribati', code: '+686' },
  { name: 'Cameroon', code: '+237' },
  { name: 'Đảo Tiệc tùng', code: '+262' },
  { name: 'Zimbabwe', code: '+263' },
  { name: 'Cộng hòa Séc', code: '+420' },
  { name: 'Campuchia', code: '+855' },
  { name: 'Gabon', code: '+241' },
  { name: 'Ghana', code: '+233' },
  { name: 'Guinea-Bissau', code: '+245' },
  { name: 'Guinea', code: '+224' },
  { name: 'Kyrgyzstan', code: '+996' },
  { name: 'Djibouti', code: '+253' },
  { name: 'Congo', code: '+242' }
];
